### ISSUE TITLE
Fixing the issue with the source path for issue.json and checklist.json

### ISSUE THREAD

**Issue by Chilico** [bugcrowdlabs/HUNT#3]
Full path to issue.json and checklist.json should be defined to work properly. 
Line 556 for hunt_scanner.py and line 161,171 for hunt_methodology.py should be edit by the user with full paths. 

Here is the fix: 
[hunt_scanner.txt](https://github.com/bugcrowdlabs/HUNT/files/1191901/hunt_scanner.txt)
[hunt_methodology.txt](https://github.com/bugcrowdlabs/HUNT/files/1191903/hunt_methodology.txt)

**Comment by swagnetow** [comment]
@JPmonglis Mind submitting this as a pull request? Thanks.

**Comment by JPmonglis** [comment]
@swagnetow I'm getting permission errors for some reason , after talking to Jason hes guide me to submitted as an issue.

**Comment by JPmonglis** [comment]
He gonna merge it tonight as he told me!

**Comment by swagnetow** [comment]
Do you mind pasting the error message you're getting? It should be in the Burp error window in Extender.

**Comment by Chilico** [comment]
@swagnetow The error was about issue.json and checklist.json cant be found.
The issue seems to be the use of relative path, after change it to full path everything worked fine

**Comment by swagnetow** [comment]
@Chilico I assume everything is working now with the current code? If so, I'll go ahead and close this issue out.

**Comment by Chilico** [comment]
@swagnetow Even with the latest updates I'm still getting the same error
 "IOError: (2, 'No such file or directory', './conf/issues.json')" 
I have tested on different systems and getting the same error. 
The only solution I found which work for me is to add the full path as you can see on my fixes. 
If you dont face the same error feel free to close this issue.

**Comment by swagnetow** [comment]
Are you by chance using Windows? I feel like that may be the issue.

**Comment by swagnetow** [comment]
@Chilico Hey, I updated the code to use absolute paths. Let me know if that works for you now.

**Comment by Chilico** [comment]
@swagnetow No I only use linux , ubuntu and arch specifically and still getting the same error.
If this is only me I'm not sure if worthing the troubleshooting for a single person as I am able to solve the problem for my self.

**Comment by swagnetow** [comment]
@Chilico I'll go ahead and close the issue out then. It's weird that you're getting path errors even after changing the code to use absolute paths.
